[package]
name = "bank_project"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Kim_Jin_Pyo"]
description = "Simple bank program"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
